<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXIGc5zI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXIGc5zI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXIGc5zI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXIGc5zI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXIGc5zI\App_KernelDevDebugContainer([
    'container.build_hash' => 'XIGc5zI',
    'container.build_id' => '70fd8b60',
    'container.build_time' => 1616361970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXIGc5zI');
