<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Service extends \App\Entity\Service implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'valideParAdmin', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'creneauBase', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'tarif', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'fournisseur'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'valideParAdmin', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'titre', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'telephone', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'adresse', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'creneauBase', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'tarif', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Service' . "\0" . 'fournisseur'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Service $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getValideParAdmin(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValideParAdmin', []);

        return parent::getValideParAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function setValideParAdmin(?bool $valideParAdmin): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValideParAdmin', [$valideParAdmin]);

        return parent::setValideParAdmin($valideParAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre(string $titre): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone(int $telephone): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse(string $adresse): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreneauBase(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreneauBase', []);

        return parent::getCreneauBase();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreneauBase(int $creneauBase): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreneauBase', [$creneauBase]);

        return parent::setCreneauBase($creneauBase);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', []);

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif(float $tarif): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', [$tarif]);

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?\App\Entity\TypeService
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?\App\Entity\TypeService $type): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getFournisseur(): ?\App\Entity\Fournisseur
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFournisseur', []);

        return parent::getFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFournisseur(?\App\Entity\Fournisseur $fournisseur): \App\Entity\Service
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFournisseur', [$fournisseur]);

        return parent::setFournisseur($fournisseur);
    }

}
