<?php

namespace ContainerXIGc5zI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VGAwwmkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vGAwwmk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vGAwwmk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'r' => ['privates', '.errored..service_locator.vGAwwmk.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.vGAwwmk": it references class "App\\Entity\\Reservation" but no such service exists.'],
        ], [
            'em' => '?',
            'r' => 'App\\Entity\\Reservation',
        ]);
    }
}
