<?php

namespace ContainerXIGc5zI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0R1NbjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0R_1Nbj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0R_1Nbj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PinsController::create' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\PinsController::index' => ['privates', '.service_locator.c4QZcn3', 'get_ServiceLocator_C4QZcn3Service', true],
            'App\\Controller\\PinsController::inscrit' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\PriseRdvController::delete' => ['privates', '.service_locator.vGAwwmk', 'get_ServiceLocator_VGAwwmkService', true],
            'App\\Controller\\PriseRdvController::edit' => ['privates', '.service_locator.J7If5lv', 'get_ServiceLocator_J7If5lvService', true],
            'App\\Controller\\PriseRdvController::index' => ['privates', '.service_locator.rIEirAv', 'get_ServiceLocator_RIEirAvService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YT8XVZ7', 'get_ServiceLocator_YT8XVZ7Service', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\PinsController:create' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\PinsController:index' => ['privates', '.service_locator.c4QZcn3', 'get_ServiceLocator_C4QZcn3Service', true],
            'App\\Controller\\PinsController:inscrit' => ['privates', '.service_locator.5miB8_X', 'get_ServiceLocator_5miB8XService', true],
            'App\\Controller\\PriseRdvController:delete' => ['privates', '.service_locator.vGAwwmk', 'get_ServiceLocator_VGAwwmkService', true],
            'App\\Controller\\PriseRdvController:edit' => ['privates', '.service_locator.J7If5lv', 'get_ServiceLocator_J7If5lvService', true],
            'App\\Controller\\PriseRdvController:index' => ['privates', '.service_locator.rIEirAv', 'get_ServiceLocator_RIEirAvService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YT8XVZ7', 'get_ServiceLocator_YT8XVZ7Service', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.CpaXrFh', 'get_ServiceLocator_CpaXrFhService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.pwZ6MTM', 'get_ServiceLocator_PwZ6MTMService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.UDgw6Ol', 'get_ServiceLocator_UDgw6OlService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\PinsController::create' => '?',
            'App\\Controller\\PinsController::index' => '?',
            'App\\Controller\\PinsController::inscrit' => '?',
            'App\\Controller\\PriseRdvController::delete' => '?',
            'App\\Controller\\PriseRdvController::edit' => '?',
            'App\\Controller\\PriseRdvController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PinsController:create' => '?',
            'App\\Controller\\PinsController:index' => '?',
            'App\\Controller\\PinsController:inscrit' => '?',
            'App\\Controller\\PriseRdvController:delete' => '?',
            'App\\Controller\\PriseRdvController:edit' => '?',
            'App\\Controller\\PriseRdvController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
