<?php

namespace ContainerXIGc5zI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J7If5lvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.J7If5lv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.J7If5lv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'f' => ['privates', '.errored..service_locator.J7If5lv.App\\Entity\\Fournisseur', NULL, 'Cannot autowire service ".service_locator.J7If5lv": it references class "App\\Entity\\Fournisseur" but no such service exists.'],
            'r' => ['privates', '.errored..service_locator.J7If5lv.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.J7If5lv": it references class "App\\Entity\\Reservation" but no such service exists.'],
        ], [
            'em' => '?',
            'f' => 'App\\Entity\\Fournisseur',
            'r' => 'App\\Entity\\Reservation',
        ]);
    }
}
